<?php /** @var $block \Snowdog\CustomDescription\Block\Adminhtml\Product\Edit\Tab\CustomDescription\Description */ ?>

<script id="custom-description-base-template" type="text/x-magento-template">
    <div class="fieldset-wrapper admin__collapsible-block-wrapper opened" id="description_<%- data.id %>">
        <div class="fieldset-wrapper-title">
            <strong
                class="admin__collapsible-title"
                data-toggle="collapse"
                data-target="#<%- data.id %>-content">
                <span id="description_<%- data.id %>_header_title"><%- data.title %></span>
            </strong>
            <div class="actions">
                <button type="button" title="<?php /* @escapeNotVerified */ echo __('Delete Description'); ?>" class="action-delete" id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_delete">
                    <span><?php /* @escapeNotVerified */ echo __('Delete Description'); ?></span>
                </button>
            </div>
            <div id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_move" data-role="draggable-handle" class="draggable-handle"
                 title="<?php /* @escapeNotVerified */ echo __('Sort Description'); ?>"></div>
        </div>
        <div class="fieldset-wrapper-content in collapse" id="<%- data.id %>-content">
            <fieldset class="fieldset">
                <fieldset class="fieldset-alt" id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>">
                    <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_is_delete" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][is_delete]" type="hidden" value=""/>
                    <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_id" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][id]" type="hidden" value="<%- data.id %>"/>
                    <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_description_id" name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][description_id]" type="hidden" value="<%- data.description_id %>"/>
                    <input name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][sort_order]" type="hidden" value="<%- data.sort_order %>"/>

                    <div class="field field-description-title">
                        <div class="control">
                            <input id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_title"
                                   name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][title]"
                                   class="required-entry input-text"
                                   type="hidden"
                            <% if (data.title) { %>
                            data-store-label="<%- data.title %>"
                            value="<%- data.title %>"
                            <% } else { %>
                            data-store-label="Description #<%- data.id %>"
                            value="Description #<%- data.id %>"
                            <% } %>
                            <% if (typeof data.scopeTitleDisabled != 'undefined' && data.scopeTitleDisabled != null) { %> disabled="disabled" <% } %>
                            >
                            <%- data.checkboxScopeTitle %>
                        </div>
                    </div>

                    <div class="field field-description-input-type required">
                        <label class="label" for="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_title">
                            <?php /* @escapeNotVerified */ echo __('Description') ?><em></em>
                        </label>
                        <div class="control description-description">
                            <textarea
                                id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_description"
                                name="<?php /* @escapeNotVerified */ echo $block->getFieldName() ?>[<%- data.id %>][description]"
                                class="custom_description admin__control-textarea required-entry"
                                rows="2"
                                cols="15"
                                title="<?php /* @escapeNotVerified */ echo __('Description') ?> <%- data.id %>"
                                style="width: 370px;"
                            ><%- data.description %></textarea>
                        </div>
                    </div>

                    <div class="field field-description-req required">
                        <label class="label" for="field-description-req">
                            <?php /* @escapeNotVerified */ echo __('Image')?><em></em>
                        </label>
                        <div class="control description-image">
                            <% if (data.image) { %>
                            <p>
                                <img style="width: 100px;" src="/media/<%- data.image %>" alt="<%- data.title %>" title="<%- data.title %>"/>
                            </p>
                            <% } %>
                            <input
                                id="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_image"
                                class="input-file <% if (!data.image){ %>required-entry<% } %>"
                                type="file"
                                name="<?php /* @escapeNotVerified */ echo $block->getFieldId() ?>_<%- data.id %>_image"
                            />
                        </div>
                    </div>
                </fieldset>
            </fieldset>
        </div>
    </div>
</script>
<script>
    require([
        "jquery",
        "Snowdog_CustomDescription/js/custom-description"
    ], function(jQuery){

        jQuery(function ($) {
            var fieldSet = $('[data-block=product-custom-description]');
            fieldSet.customDescription(<?php /* @escapeNotVerified */ echo $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode(
                [
                    'fieldId' => $block->getFieldId(),
                    'formKey' => $block->getFormKey(),
                    'itemCount' => $block->getItemCount()
                ]
            )?>);

            <?php foreach($this->getCustomDescription() as $detDesc): ?>
                fieldSet.customDescription('addDescription', <?php /* @escapeNotVerified */ echo $detDesc->toJson() ?>);
            <?php endforeach; ?>
        });
    });
</script>