<?php
/** @var $block \Snowdog\CustomDescription\Block\Catalog\Product\View\CustomDescription */
/** @var $customDescription \Snowdog\CustomDescription\Model\Resource\CustomDescription\Collection */
$customDescription = $block->getCustomDescription();
?>
<?php if ($customDescription->getSize()) : ?>
    <div class="block block-custom-description">
        <div class="block-title title">
            <strong id="block-custom-description-heading">
                <?php echo __("Structured Description") ?>
            </strong>
        </div>
        <div class="block-content content">
            <table>
                <thead>
                    <tr>
                        <th>
                            <?php echo __("Image"); ?>
                        </th>
                        <th>
                            <?php echo __("Description"); ?>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($customDescription as $d): ?>
                        <tr>
                            <td>
                                <div class="img-item-custom-description">
                                    <img style="width:200px;"
                                         src="<?php echo $block->getImageSrc($d->getData('image')); ?>"
                                         title="<?php echo $d->getData('title'); ?>"
                                         alt="<?php echo $d->getData('title'); ?>"
                                    />
                                </div>
                            </td>
                            <td>
                                <div class="text-item-custom-description">
                                    <?php echo $d->getData('description'); ?>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
<?php endif;?>
