<?php
/** @var $block \Snowdog\CustomDescription\Block\Catalog\Product\View\CustomDescription */
$customDescription = $block->getCustomDescription();
?>
<?php if (count($customDescription)) : ?>
    <div class="block block-custom-description">
        <div class="block-title title">
            <strong id="block-custom-description-heading">
                <?php echo __("Custom Description") ?>
            </strong>
        </div>
        <div class="block-content content">
            <?php foreach($customDescription as $d): ?>
                <div class="block block-item-custom-description">
                    <div class="img-item-custom-description">
                        <img src="/media/<?php echo $d['image']; ?>" title="<?php echo $d['title']; ?>" alt="<?php echo $d['title']; ?>"/>
                    </div>
                    <div class="text-item-custom-description">
                        <?php echo $d['description']; ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif;?>
